#!/bin/bash

fun_dtproxy() {
    function mostrar_menu_security() {
        clear
        echo -e "\E[44;1;37m       WEBSOCKET SECURITY        \E[0m"
        echo ""
        echo -e "\033[1;36m1.\033[0m \033[1;33mATIVAR WSSSECURITY\033[0m"
        echo -e "\033[1;36m2.\033[0m \033[1;33mDESATIVAR WSSSECURITY\033[0m"
        echo -e "\033[1;36m3.\033[0m \033[1;33mVOLTAR\033[0m"
        echo ""
        echo -ne "\033[1;32mEscolha uma opção: \033[0m"
    }

    function ativar_proxy() {
        process_name="WssSecurity"
        read -p "Insira a porta desejada (por exemplo, 80): " porta

        # Verificar se a porta já está em uso pelo processo "WssSecurity"
        if lsof -i :$porta -t &>/dev/null; then
            echo "A porta $porta já está em uso pelo processo '$process_name'."
        else
            read -p "Insira a MENSAGEM: " mensagem
            screen -dmS "$process_name" /etc/SSHPlus/WebSocket -proxy_port "0.0.0.0:$porta" -msg "$mensagem"
            echo "Proxy ativado na porta $porta com a mensagem: $mensagem e o nome do processo '$process_name'."
        fi
    }

    function desativar_proxy() {
        process_name="WssSecurity"
        if pgrep -f "$process_name" > /dev/null; then
            pkill -f "$process_name"
            echo "Proxy na porta com o nome do processo '$process_name' foi desativado."
        else
            echo "Nenhum proxy com o nome do processo '$process_name' em execução."
        fi
    }

    function menu_security() {
        while true; do
            mostrar_menu_security
            read opcao
            case $opcao in
                1)
                    ativar_proxy
                    read -p "Pressione Enter para continuar..."
                    ;;
                2)
                    desativar_proxy
                    read -p "Pressione Enter para continuar..."
                    ;;
                3)
                    echo "Saindo do dtproxy."
                    exit
                    ;;
                *)
                    echo "Opção inválida. Tente novamente."
                    read -p "Pressione Enter para continuar..."
                    ;;
            esac
        done
    }

    # Iniciar o menu de segurança
    menu_security
}
fun_dtproxy